version: "3"
networks:
  sde:
    external: true

volumes:
  mongodata:
    external: true

services:
  mongo-exchanges:
    image: mongo:4.2.18-rc0-bionic
    logging:
      driver: none
    restart: on-failure
    ports:
      - 27017:27017
    volumes:
      - mongodata:/data/db
    networks:
      - sde
  data-adapter-exchanges:
    build: ./data-adapter
    restart: on-failure
    depends_on: 
      - mongo-exchanges
    ports:
      - 2901:2901
    networks:
      - sde
  exchanges-adapter-exchanges:
    build: ./exchanges-adapter
    restart: on-failure
    depends_on:
      - data-adapter-exchanges
    networks:
      - sde
  business-logic-exchanges:
    build: ./business-logic
    restart: on-failure
    depends_on:
      - data-adapter-exchanges
    ports:
      - 2902:2902
    networks:
      - sde
  process-centric-exchanges:
    build: ./process-centric
    restart: on-failure
    depends_on:
      - data-adapter-exchanges
      - business-logic-exchanges
    ports:
      - 2900:8000
    networks:
      - sde